### ISSUE TITLE
route conflict for interesting case..

### ISSUE THREAD

**Issue by donileo** [julienschmidt/httprouter#120]
POST "/person/register/", register)
POST "/person/login/", login)
POST "/person/:uid/logout/", logout)

Any reason why the logout conflicts with the register and login?

**Comment by Thomasdezeeuw** [comment]
Because both `login` and `register` can be the `uid` parameter.

**Comment by donileo** [comment]
even if thats so.. /person/login/logout should not match /person/login/

**Comment by julienschmidt** [comment]
> /person/login/logout should not match /person/login/

It does not match, however it would match "/person/:uid/logout/".

> The following case doesn't cause a conflict and going by the above shouldn't it?
> 
> PUT "/person/:uid/mode/"
> PUT "/person/:uid/"
> PUT "/person/:uid/location/"

It does not cause a conflict since you register `/person/:uid/` and the subroutes `/person/:uid/mode/` and `/person/:uid/location/`. The `:uid` path segment stays the same. If you would try to register `/person/login/`, `login` and `:uid` would conflict.

**Comment by rocwong** [comment]
I have the same issue.
How is the progress of v2 now ? @julienschmidt
