### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by kron4eg** [julienschmidt/httprouter#148]
@julienschmidt if you take closer look https://github.com/kataras/iris/blob/master/http.go#L654 and lower you would clearly see that it's code from this project, with changed functions and variables names.

I've tried to contact author ( @kataras ) of violating package here: https://github.com/kataras/iris/issues/230, you can see the unfortunate result.

**Comment by sergeyklay** [comment]
![screenshot at jun 25 16-16-17](https://cloud.githubusercontent.com/assets/1256298/16356913/2c7adc82-3af0-11e6-937c-ff88192aedaf.png)

**Comment by sergeyklay** [comment]
![screenshot at jun 25 16-16-17](https://cloud.githubusercontent.com/assets/1256298/16356916/433edf04-3af0-11e6-846b-b1c5c1156778.png)

**Comment by rjeczalik** [comment]
![pic](http://i.imgur.com/rC9E70F.jpg)

**Comment by kataras** [comment]
@kron4eg @sergeyklay  You should Read the CONTRIBUTING.MD and THIRDPARTY.MD, if you did that you would see that I added the httprouter as other libraries that Iris uses, lol **READ FIRST*

**Comment by AlekSi** [comment]
@kataras Probably you should stop editing other people's comments?

**Comment by kataras** [comment]
@kron4eg @sergeyklay

Edited by author, reason: [guidelines](https://github.com/kataras/iris/blob/master/CONTRIBUTING.md) skipped by the commentator.

However I answer to him, because propably he is a newcomer:`  Please read the`  [THIRDPARTY](https://github.com/kataras/iris/blob/master/THIRDPARTY.md)`  to understand what you wrote.`  

You should read the [CONTRIBUTION](https://github.com/kataras/iris/blob/master/CONTRIBUTING.md) file before post any new issue, you are welcome to our [chat](https://gitter.im/kataras/iris) also.

@julienschmidt already knows that, I always have his link (on comments, package name and now on an MD file). I do not make license violation, I have all libraries listed, I have no reason to hide while we are faster..

**Comment by julienschmidt** [comment]
@kataras Nice try. Unfortunately you pushed those edits after you the issue was opened.
Sometimes faking commit dates isn't enough.

**Comment by julienschmidt** [comment]
https://www.reddit.com/r/golang/comments/4bw0yk/go_web_frameworks_a_benchmark_only_comparison/d1dte0i was also a nice attempt

**Comment by kataras** [comment]
@julienschmidt Go back before rc.3 (before 3-4 days)  and see where was your name please ( it was on the START OF THE MAIN ROUTER PACKAGE )

**Comment by kataras** [comment]
@julienschmidt  man your benchmark suite is nothing... and you know that please you should learn from this benchmark suite: https://github.com/smallnest/go-web-framework-benchmark

**Comment by kataras** [comment]
@julienschmidt  I have listed all libraries where is the problem with you anyway?

**Comment by kataras** [comment]
@AlekSi If they read the README I am answering very polite ( only 4 issues from the 204 have been edited).

**Comment by kron4eg** [comment]
@kataras I'm sorry, but don't have to stat and watch your project to point that it violates license of other people's code.

**Comment by kataras** [comment]
Yes or chat with me, I am not violates anything, you just hate Iris because it lives 3 months and has more stars than projects (like this) which exists more than years..anyway

**Comment by AlekSi** [comment]
> If they read the README I am answering very polite ( only 4 issues from the 204 have been edited).

First, you are not [polite](https://golang.org/conduct).

Second:
1. https://github.com/kataras/iris/issues/200
2. https://github.com/kataras/iris/issues/208
3. https://github.com/kataras/iris/issues/211
4. https://github.com/kataras/iris/issues/219
5. https://github.com/kataras/iris/issues/225

I stopped at five because you said four. One can find much more.

**Comment by kataras** [comment]
@kron4eg 

Yes or you could chat with me on the global iris chat, I am not violating anything, you just hate Iris because it lives 3 months and has more stars than projects (like this) which exists more than years..anyway

I answered to all questions I have nothing to hide, all libraries are listed and before your comment, and if you look back to the history you can also see julien's name in the old router, but he has some problems with me for the reason I wrote before. I have no itention to violate anything ...you should understood that.. ( although his source is slower than Iris' muxEntry's, he should learn from iris not hate it. ). End .-

**Comment by kataras** [comment]
@kron4eg  

I am polite but my english expression is not so good, I am not native english sepaker, you missunderstood and you ever don't read my answers, so we stop now.

**Comment by julienschmidt** [comment]
@kataras I have exactly two problems with you:
1. Your lack of respect and attempts to badmouth other people. Yes, you seem to like those GitHub stars, but don't try to get them by false claims and on the cost of others. That is not how (unsponsored) FLOSS should work (see the reddit example, unless someone managed to link your Hotmail address to their GitHub account, that was you)
2. [httprouter/LICENSE](https://github.com/julienschmidt/httprouter/blob/master/LICENSE) is the other one

**Comment by julienschmidt** [comment]
See also https://github.com/kataras/iris/issues/15

**Comment by kataras** [comment]
@julienschmidt Did you know that I left from university for iris? 

> See also kataras/iris#15

That I told at the first place and you start to speak me like I am your wife..

**Comment by julienschmidt** [comment]
@kataras Read the license and respect it. And stop using HttpRouter or any other of my software for questionable comparisons.

The other option is a cease-and-desist letter. We are both in the EU after all.
