### ISSUE TITLE
Sub router

### ISSUE THREAD

**Issue by gsquire** [julienschmidt/httprouter#154]
I searched through the issues but couldn't find anything for sub routers with paths. I don't care about subdomains.

My use case is for API versioning. Here is a snippet from the Gorilla [mux](http://www.gorillatoolkit.org/pkg/mux):

```go
r := mux.NewRouter()
s := r.PathPrefix("/products").Subrouter()
// "/products/"
s.HandleFunc("/", ProductsHandler)
// "/products/{key}/"
s.HandleFunc("/{key}/", ProductHandler)
// "/products/{key}/details"
s.HandleFunc("/{key}/details", ProductDetailsHandler)
```

It would be sweet to have a sub router for each version prefix. Is this currently possible or something you could add?

Forgive me if I missed something in the README or documentation.

**Comment by rickb777** [comment]
Unlike Gorilla's router, there's no performance gain from using subrouting, because the trie algorithm already handles this inherently.

So the question becomes one of how to construct formulaic paths. Although it would be a nice-to-have feature, my approach to this has been to wrap a *Router within my own path builder code instead.

**Comment by gsquire** [comment]
I'm less interested in performance than being able to unify routes based on a common path. I know how well this library performs already :)

**Comment by julienschmidt** [comment]
See #89 
Working on it!

**Comment by jub0bs** [comment]
My two cents: one reason subrouters would be useful is for applying some middleware to only a subrouter.

For instance, I'd like to adapt [this `net/http` v1.22 program](https://github.com/jub0bs/cors?tab=readme-ov-file#example) to `julienschmidt/httprouter`, but I currently cannot because there's no way to bind a subrouter to a path without also specifying a method.

**Comment by letmestudy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
