### ISSUE TITLE
Idea: allow dynamic route changes at runtime in v2

### ISSUE THREAD

**Issue by mbertschler** [julienschmidt/httprouter#173]
At first I want to congratulate you to this awesome performant library. I saw that you started planning a v2.

I thought maybe the v2 could allow changing the router while it is in use. I know this already works to some extent, but to fully use it some enhancements would be needed.

### 1. Remove existing handlers
One thing that should be possible is unregistering existing handlers. I bet this is easily implemented in a hacky way, but probably not so simple to do if the function also cleans up the tree without this route

### 2. Registering routes without panicking
The functions that register routes could return an `error` instead of panicking, or there should be a function that checks if a route with a given path is possible. I would prefer if the registering functions would return an error value.

What do you think of that?

**Comment by Thomasdezeeuw** [comment]
I think this shouldn't be in this library. If you want to modify the router in some way while using it you'll need some form of locking. Using locks reduces performance, while one of the main features of this package is performance. A second argument against this is that this probably not much used, considering this is the first request for it (I think).

Why not make it a wrapper package around this package? This way people can choose to take a performance hit if they want the functionality.

As for panicking instead of returning an error; it doesn't make sense if the first idea doesn't get added to the package. Because you want to know at startup (preferably while developing or testing) that your routes are broken. But if you create a dynamic router package around this package, it would make more sense to return errors.

**Comment by julienschmidt** [comment]
That sounds like an anti-feature to me.
URLs and thus probably also the registered routes are supposed to be static. If you need "dynamic" segments, e.g. for certain items that might be created during runtime, like articles or users, then you should use the path parameters / wildcards instead.

Moreover, changing the tree at runtime is not that trivial. Extending it is possible with locking, but removing routes is rather complicated.

**Comment by mbertschler** [comment]
Okay I see your points. Thanks for the explanation.
