### ISSUE TITLE
template

### ISSUE THREAD

**Issue by Slava1234** [julienschmidt/httprouter#188]
how to execute a template ?

**Comment by Thomasdezeeuw** [comment]
Do you mean https://golang.org/pkg/html/template/#Template.Execute? Because I think that is rather outside of the scope of this package.

**Comment by julienschmidt** [comment]
This package just provides HTTP request->handler function routing. Any further functionality like integration of template engines is not provided and should be part of higher-level frameworks.

In order to execute a template, you have to manually do so in the respective handler function. For example with html/template from the standard library, you could first parse the templates from files with https://golang.org/pkg/html/template/#ParseFiles, save the returned `*Template` as a global variable and then execute it within the handler:

```go
var tpl *Template

...

func MyHandler(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	data := ....
	if err := tpl.ExecuteTemplate(w, "mytemplatename", data); err != nil {
		....
	}
}
```
