### ISSUE TITLE
Question on Params

### ISSUE THREAD

**Issue by jackspirou** [julienschmidt/httprouter#61]
Hi @julienschmidt 

Not so much an issue, as much as a question.

Just wondering why `Param` is a `struct` instead of a `map`.  
Wouldn't it be more efficient to say `if value, ok := ps["somekey"]; ok { foo(value) }` ?

Since `Param` is a `struct` `ByName(name string)` looks like it iterates through the array of `Param`s until a string match its found.  I totally get that `ps[0]` is slightly more performant, but wouldn't a map be more useful for string matching?  Maybe not? 

Just curious what influenced the data structure choice for `Param`!  Im sure there is a good reason! 

Thanks again for this router!!!

**Comment by julienschmidt** [comment]
Good question. The hashing of the string is actually more expensive than just comparing it with the names. 
Now we all learned that hash map lookups are O(1) and the comparing is O(n), but in this case n is very small, since n is just the number of parameters in the matched URL pattern. I can't think of a good URL structure with n ≥ 10, usually it is just 0 ≤ n ≤ 3.
And the hash map lookup is actually O(1+c), where c is a quite big constant in this case.

Moreover hash maps need a lot more memory.
The router initially used maps ;)

**Comment by jackspirou** [comment]
@julienschmidt So glad you addressed the O(1) vs O(n).  Great answer!

**Comment by jackspirou** [comment]
@julienschmidt I noticed that Brad Fitzpatrick suggested using an array instead of a map for part of the HTTP2 golang implementation.  Probably because that particular map only contains 10 elements.  I wonder what the performance cutoff is in go for maps?

https://www.youtube.com/watch?v=gAfoLwog_MA&feature=youtu.be&t=21m18s 

Well played!
